version: '2'

services:
  db:
    env_file: ./config/docker/env/db/dev

  backend:
    links:
      - db
      - webpack
    volumes:
      - "./config/php/dev.ini:/etc/php7/conf.d/zzzz-dev.ini:ro"
      - "./config/nginx/inc.d:/etc/nginx/inc.d:ro"
      - "./config/backend/dev:/var/www/wp-configs:ro"
    env_file: ./config/docker/env/backend/dev

  webpack:
    image: kucrut/yarn
    container_name: wp-id.org-webpack
    working_dir: /app
    networks:
      - default
    volumes:
      - "./data/webpack:/app"
      - "./data/content/themes:/app/themes"
      - "./data/content/plugins:/app/plugins"
    command: [ "sh", "-c", "mkdir /tmp/yarn && export HOME=/tmp/yarn && yarn install && yarn start" ]
