version: '3'

services:
  db:
    image: kucrut/mariadb
    restart: always
    networks:
      - default
    volumes:
      - "./data/db:/var/lib/mysql"

  backend:
    image: kucrut/wordpress
    restart: always
    depends_on:
      - db
    links:
      - db
    networks:
      - default
